### PR TITLE
Fix typo in readme

### PR DESCRIPTION
**Pull request by 0xflotus**

### CODE REVIEW

**Comment by sholladay** [comment]
Thank you! :)

**Comment by sindresorhus** [comment]
It's not a typo: https://en.wiktionary.org/wiki/cancelation

**Comment by sholladay** [comment]
@sindresorhus that very page says:

> the word cancellation is still much more widely used than the variant cancelation

**Comment by 0xflotus** [comment]
Oh sorry, I didn't know the version *cancelation*

**Comment by sindresorhus** [comment]
I'm ok with the change, just wanted to point out it was not a typo.

**Comment by 0xflotus** [comment]
> I'm ok with the change, just wanted to point out it was not a typo.

Cool.

**Pull request merged**
