### PR TITLE
Declare package as module and specify exports files

### PR DESCRIPTION
**Pull request by ubergesundheit**
Follow up to #242 after a discussion there.

This pull request adds the fields `type` and `exports` to `package.json`.

### CODE REVIEW

**Comment by ubergesundheit** [comment]
Mh could it be possible that declaring `"type": "module"` breaks this for all node versions below 13? Wdyt about just specifying the `exports` field.

**Comment by sindresorhus** [comment]
Why would it break? `type` is a new property for Node.js 13.

**Comment by ubergesundheit** [comment]
Tests with node 12 and 10 fail with error `AVA cannot yet load ESM files.`

**Comment by sholladay** [comment]
Tests are also failing for me locally with Node v13.8.0. Lots of errors like...

```
Uncaught exception in test/browser.js


file:///private/tmp/ky/test/_require.js:1
import fetch, {Headers, Request, Response} from 'node-fetch';
               ^^^^^^^
SyntaxError: The requested module 'node-fetch' does not provide an export named 'Headers'
```

**Comment by sindresorhus** [comment]
@ubergesundheit Bump :)

**Comment by ubergesundheit** [comment]
I dont have the time right now to push this further. Feel free to pick up or close. Sorry :(

**Comment by sholladay** [comment]
I played with it a bit and couldn't figure it out. Seems like it should work, but `"type": "module"` changes something in the tooling that causes imports within the test helper to fail. Probably something in AVA or the `esm` package.

**Comment by sindresorhus** [comment]
Slightly related, but Webpack 5 will finally support the `exports` field: https://github.com/webpack/webpack/releases/tag/v5.0.0-beta.18

**Comment by rifler** [comment]
> Tests are also failing for me locally with Node v13.8.0. Lots of errors like...
> 
> ```
> Uncaught exception in test/browser.js
> 
> 
> file:///private/tmp/ky/test/_require.js:1
> import fetch, {Headers, Request, Response} from 'node-fetch';
>                ^^^^^^^
> SyntaxError: The requested module 'node-fetch' does not provide an export named 'Headers'
> ```

Maybe the thing is that node cannot do named imports from CJS package, you have to write

```
import fetch from 'node-fetch';

const { Headers, Request, Response } = fetch;
```

you can try 14.13.0, where support for named import was added

https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V14.md#2020-09-29-version-14130-current-mylesborins

**Comment by sindresorhus** [comment]
Closing for lack of activity. Continued in https://github.com/sindresorhus/ky/issues/283.

**Comment by ubergesundheit** [comment]
Sorry for the lack of activity :( 

I'll try to read the linked issue . If there is anything I could do, LMK

**Comment by sholladay** [comment]
@ubergesundheit could you try the solution suggested in https://github.com/sindresorhus/ky/pull/244#issuecomment-703902208? Seems promising.

**Pull request closed without merging**
