### PR TITLE
Expose Options interface

### PR DESCRIPTION
**Pull request by jas0ncn**
- Expose `OptionsWithoutBody` and `OptionsWithBody`
- `patch` has body!

### CODE REVIEW

**Comment by joaovieira** [comment]
@jas0ncn just noticed we've done different things for the same problem. See https://github.com/sindresorhus/ky/pull/162

I'd rather only export a set of `Options` as it's already the case. But make sure that `ky()` supports them. In my solution you can use `Options` directly as so:

```ts
import ky, { Options } from 'ky';

const postOptions: Options = {
  method: 'post',
  json: { ok: true }  
}; // OK

const getOptions: Options = {
  method: 'get',
  json: { ok: true }
}; // OK

ky('https://example.com', postOptions); // OK
ky('https://example.com', getOptions); // Error
```

**Comment by jas0ncn** [comment]
Yes, I know. But if I want to do the same thing on each method request, I can't  define options type on the function I create. For example:

```typescript
import ky, { Options } from 'ky'

export async function request (url: string, options: Options) {
  try {
    const res = ky(url, options) // options type error
    return [res.json(), e]
  } catch (e) {
    return [null, e]
  }
}
```

**Comment by jas0ncn** [comment]
Duplicate of #162

**Comment by joaovieira** [comment]
Actually, didn't work as I expected 😬 but I've updated and should be good now. I've export `Input` and the merged `Options = OptionsWithoutBody | OptionsWithBody`.

**Pull request closed without merging**
