### PR TITLE
Clean up orphan ReadableStream remaining during parsing response (#648)

### PR DESCRIPTION
**Pull request by HaidongPang**

### CODE REVIEW

**Comment by gregory** [comment]
@HaidongPang i was just looking into something similar, [it appears that the response is cloned before being passed to each afterResponse hooks](https://github.com/sindresorhus/ky/blob/main/source/core/Ky.ts#L45) which will create ReadableStream branches, which will force the runtime to buffer the entire body of the stream in memory multiple times without certainty that it'll ever be consumed... 

@sindresorhus Could you elaborate on why you felt that you had to do that? 

Thanks for your amazing work btw 🙏

**Comment by HaidongPang** [comment]
@gregory

I suspect that @sindresorhus does not want the ReadableStream of response to be consumed in the afterResponse hooks, which would result in incomplete response data being returned.

In short, you can view the response object that is exactly the same as the original response in afterResponse hooks, but you should not modify the original response.

**Comment by gregory** [comment]
> @gregory
> 
> I suspect that @sindresorhus does not want the ReadableStream of response to be consumed in the afterResponse hooks, which would result in incomplete response data being returned.
> 
> In short, you can view the response object that is exactly the same as the original response in afterResponse hooks, but you should not modify the original response.

I understand, but that would be the responsibility of the consumer. 
Ie: in the hook: 
```
(req, {context}, res) => {
const headers = res.headers() 
const clone = res.clone()
}```

**Comment by sholladay** [comment]
We could leave cloning to the consumer, but it's not very ergonomic and definitely a footgun of its own.

One possible solution might be to override the body methods so they first clone the response before consuming the stream.

**Comment by gregory** [comment]
> We could leave cloning to the consumer, but it's not very ergonomic and definitely a footgun of its own.
> 
> One possible solution might be to override the body methods of the response given to hooks, so they first clone the response before consuming the stream.

that's a good idea.

**Comment by HaidongPang** [comment]
Will these two patches be considered for merging in future versions?
Related to :[#650](https://github.com/sindresorhus/ky/issues/650)

**Comment by sholladay** [comment]
Closing in favor of #661.

After careful review, I determined that we don't need to clone the response at all in this particular case. 😀

**Pull request closed without merging**
