### PR TITLE
update(readme): fix svg on npm

### PR DESCRIPTION
**Pull request by fouad**

### CODE REVIEW

**Comment by sindresorhus** [comment]
No thanks. This should be fixed by npm instead. Open an issue here: https://github.com/npm/marky-markdown

**Comment by fouad** [comment]
@sindresorhus I don't think that's something they can fix. The issue is that the [image hosted by GitHub](https://raw.githubusercontent.com/sindresorhus/ky/HEAD/media/logo.svg) doesn't have a content-type. If you're cool with a `png` instead of an `svg`, that'd work too.

**Comment by sindresorhus** [comment]
Sorry, I'm not interested in doing anything special for npm.

**Comment by sindresorhus** [comment]
> The issue is that the image hosted by GitHub doesn't have a content-type.

It does if you add `?sanitize=true`. https://raw.githubusercontent.com/sindresorhus/ky/HEAD/media/logo.svg?sanitize=true

**Comment by fouad** [comment]
Ahh gotcha! didn't know that — will file an issue in `marky-markdown` with that query param as expected behavior for svg's

**Pull request closed without merging**
