### PR TITLE
Cypress integration

### PR DESCRIPTION
**Pull request by dangdennis**
Setting up cypress for integration tests. Still lots of work to be done.

1. Remove example test files
2. Set up one proper integration test for Ky streams as template
3. Include cypress into npm run test

### CODE REVIEW

**Comment by dangdennis** [comment]
Hey guys,

I cleaned up the initial Cypress files for this branch. 

Any mock data or files required for Cypress tests will reside within `/cypress/fixtures/**`. All other tests should be placed inside `/cypress/integrations`.

`npm run test` will run cypress as well.

**Comment by dangdennis** [comment]
How should we update the documentation to mirror testing practices?

**Comment by sholladay** [comment]
Still looks like there are a lot of unnecessary lines in here, commented out files, etc. I also don't see any tests. Is there a particular area you need help on to write the first test?

As an aside, the diff is confusing, as it includes recent changes from `master`.

**Comment by venikman** [comment]
Very excited to help with `cypress`. But would like to get some guidelines to start from

**Comment by dangdennis** [comment]
@sholladay 

Since this PR is separate from the stream feature, I didn't add any test yet. But I just realized what happened - this was an older branch off my stream branch (oops) that rebased new code changes.

I will create a new PR to clean up the diffs and only include Cypress setup.

Regarding some of the files commented out: Those came with Cypress, and are examples of further Cypress customization. I'll get rid of them if you don't think they will hold significant value.

@venikman Hey! I'll do a new PR for the Cypress setup, and we can talk about testing there. As well as some best practices. As it is, it's best if we keep things as simple as possible.

**Comment by dangdennis** [comment]
Referencing the new PR here #51

**Pull request closed without merging**
