### PR TITLE
Setup clean Cypress

### PR DESCRIPTION
**Pull request by dangdennis**
Fixtures, such as json or images, will be placed inside /cypress/fixtures

All integration tests should be named `[filename].spec.js` and placed inside /cypress/integration.

### CODE REVIEW

**Comment by dangdennis** [comment]
Why have all my PRs been failing? 😢

**Comment by sholladay** [comment]
Very strange error there. Something about TypeScript and jQuery. Does `npm test` pass for you locally?

**Comment by sindresorhus** [comment]
Related: https://github.com/cypress-io/cypress/issues/2363#issuecomment-426515098

**Comment by dangdennis** [comment]
Will upgrade Cypress to the next available minor release to fix this build issue when that patch comes around.

**Comment by sindresorhus** [comment]
I found a way to work around the Cypress issue and I implemented this integration properly. I appreciate you starting this though, @dangdennis :)

**Pull request closed without merging**
